// Run with scripts/test_terminal.sh. This compiles alongside the production
// TerminalPanel; it does not mock SwiftTerm, AppKit, zsh, or the PTY transport.
// The window is never shown. User shell startup files and history are untouched.
import AppKit
import Darwin
import SwiftTerm

private struct CheckFailure: Error, CustomStringConvertible {
    let description: String
}

/// Capture the bytes generated by real AppKit input before they enter a PTY.
@MainActor
private final class InputCapture: NSObject, @preconcurrency TerminalViewDelegate {
    var bytes: [UInt8] = []
    func send(source: TerminalView, data: ArraySlice<UInt8>) { bytes += data }
    func sizeChanged(source: TerminalView, newCols: Int, newRows: Int) {}
    func setTerminalTitle(source: TerminalView, title: String) {}
    func hostCurrentDirectoryUpdate(source: TerminalView, directory: String?) {}
    func scrolled(source: TerminalView, position: Double) {}
    func requestOpenLink(source: TerminalView, link: String, params: [String: String]) {}
    func bell(source: TerminalView) {}
    func clipboardCopy(source: TerminalView, content: Data) {}
    func iTermContent(source: TerminalView, content: ArraySlice<UInt8>) {}
    func rangeChanged(source: TerminalView, startY: Int, endY: Int) {}
}

@main
@MainActor
private struct TerminalPanelTests {
    private static var checksPassed = 0

    static func main() {
        do {
            try run()
            print("PASS: All \(checksPassed) native terminal runtime checks passed.")
        } catch {
            // run() unwinds its cleanup before a failure is reported or the process exits.
            print("FAIL: \(error)")
            print("RESULT: Failed after \(checksPassed) successful runtime checks.")
            Darwin.exit(1)
        }
    }

    private static func check(_ condition: @autoclosure () -> Bool, _ label: String) throws {
        guard condition() else { throw CheckFailure(description: label) }
        checksPassed += 1
        print("PASS: \(label)")
        fflush(stdout)
    }

    private static func require<T>(_ value: T?, _ label: String) throws -> T {
        guard let value else { throw CheckFailure(description: label) }
        return value
    }

    private static func pumpEvents(for duration: TimeInterval) {
        let deadline = ProcessInfo.processInfo.systemUptime + duration
        while ProcessInfo.processInfo.systemUptime < deadline {
            RunLoop.current.run(until: Date().addingTimeInterval(0.01))
        }
    }

    private static func wait(
        _ label: String, timeout: TimeInterval = 8, until condition: () -> Bool
    ) throws {
        let deadline = ProcessInfo.processInfo.systemUptime + timeout
        while !condition(), ProcessInfo.processInfo.systemUptime < deadline {
            pumpEvents(for: 0.02)
        }
        try check(condition(), label)
    }

    private static func descendants(of view: NSView) -> [NSView] {
        view.subviews.flatMap { [$0] + descendants(of: $0) }
    }

    private static func terminals(in panel: TerminalPanel) -> [LocalProcessTerminalView] {
        descendants(of: panel).compactMap { $0 as? LocalProcessTerminalView }
    }

    private static func text(in terminal: LocalProcessTerminalView) -> String {
        String(decoding: terminal.getTerminal().getBufferAsData(), as: UTF8.self)
    }

    private static func checkPhysicalDirectory(
        _ expected: URL, in terminal: LocalProcessTerminalView, marker: String, label: String
    ) throws {
        // PWD is also provided in the launch environment, so verify the actual process
        // directory with an external pwd. Base64 survives wrapping at spaces in long paths.
        // Foundation may shorten /private/tmp back to /tmp even after resolving
        // symlinks. Match the POSIX path that /bin/pwd -P actually prints.
        let resolved = try require(realpath(expected.path, nil), "resolve physical test directory")
        defer { free(resolved) }
        let physicalPath = String(cString: resolved) + "\n"
        let encoded = Data(physicalPath.utf8).base64EncodedString()
        terminal.send(txt: "printf '\\n\(marker)_%s\\n' \"$(/bin/pwd -P | /usr/bin/base64)\"\r")
        try wait(label) {
            text(in: terminal).replacingOccurrences(of: "\n", with: "").contains("\(marker)_\(encoded)")
        }
    }

    private static func child(inSession shell: pid_t) -> pid_t? {
        let capacity = max(64, Int(proc_listallpids(nil, 0)) + 64)
        var pids = [pid_t](repeating: 0, count: capacity)
        let count = pids.withUnsafeMutableBytes { proc_listallpids($0.baseAddress, Int32($0.count)) }
        return pids.prefix(max(0, min(Int(count), capacity))).first {
            $0 > 1 && $0 != shell && getsid($0) == shell
        }
    }

    private static func isGone(_ pid: pid_t) -> Bool {
        Darwin.kill(pid, 0) == -1 && errno == ESRCH
    }

    private static func checkKeyboardInput(_ terminal: LocalProcessTerminalView, window: NSWindow) throws {
        let original = terminal.terminalDelegate
        let capture = InputCapture()
        terminal.terminalDelegate = capture
        defer { terminal.terminalDelegate = original }
        // characters is the text produced by a layout; charactersIgnoringModifiers
        // is the physical key without Option. Do not change the user's input source.
        for (text, physical, flags, keyCode) in [
            ("[", "5", NSEvent.ModifierFlags.option, UInt16(23)),
            ("]", "6", NSEvent.ModifierFlags.option, UInt16(22)),
            (">", "1", NSEvent.ModifierFlags.option, UInt16(18)),
            (">", ">", NSEvent.ModifierFlags.shift, UInt16(47)),
            ("[", "[", NSEvent.ModifierFlags(), UInt16(33)),
            ("€", "2", NSEvent.ModifierFlags.option, UInt16(19))
        ] {
            capture.bytes.removeAll()
            let event = try require(NSEvent.keyEvent(
                with: .keyDown, location: .zero, modifierFlags: flags, timestamp: 0,
                windowNumber: window.windowNumber, context: nil, characters: text,
                charactersIgnoringModifiers: physical, isARepeat: false, keyCode: keyCode
            ), "construct layout-aware keyboard event")
            terminal.keyDown(with: event)
            try check(capture.bytes == Array(text.utf8),
                      "layout text \(text) reaches the terminal as UTF-8, without a Meta prefix (got \(capture.bytes))")
        }
        // Composed text still uses the input-method path.
        capture.bytes.removeAll()
        terminal.insertText("é", replacementRange: NSRange(location: NSNotFound, length: 0))
        try check(capture.bytes == Array("é".utf8), "composed Unicode text is preserved")
        capture.bytes.removeAll()
        for character in ["\u{1b}", "b"] {
            let event = try require(NSEvent.keyEvent(
                with: .keyDown, location: .zero, modifierFlags: [], timestamp: 0,
                windowNumber: window.windowNumber, context: nil, characters: character,
                charactersIgnoringModifiers: character, isARepeat: false,
                keyCode: character == "b" ? 11 : 53
            ), "construct explicit Meta sequence")
            terminal.keyDown(with: event)
        }
        try check(capture.bytes == [27, 98], "Escape followed by a key still sends a Meta shortcut")
    }

    private static func wheel(_ delta: Int32, precise: Bool = false,
                              flags: CGEventFlags = []) throws -> NSEvent {
        let event = try require(CGEvent(scrollWheelEvent2Source: nil, units: precise ? .pixel : .line,
            wheelCount: 1, wheel1: delta, wheel2: 0, wheel3: 0), "construct wheel event")
        event.flags = flags
        return try require(NSEvent(cgEvent: event), "construct native wheel event")
    }

    private static func checkWheelInput(_ terminal: LocalProcessTerminalView) throws {
        let original = terminal.terminalDelegate
        let capture = InputCapture()
        terminal.terminalDelegate = capture
        defer {
            terminal.feed(text: "\u{1b}[?1000l\u{1b}[?1006l")
            terminal.allowMouseReporting = true
            terminal.terminalDelegate = original
        }
        func reports() throws -> [[Int]] {
            try String(decoding: capture.bytes, as: UTF8.self).split(separator: "\u{1b}").map { packet in
                guard packet.hasPrefix("[<"), packet.last == "M" else {
                    throw CheckFailure(description: "invalid SGR wheel packet: \(packet)")
                }
                let values = packet.dropFirst(2).dropLast().split(separator: ";").compactMap { Int($0) }
                guard values.count == 3 else { throw CheckFailure(description: "invalid SGR coordinates") }
                return values
            }
        }
        let up = try wheel(1), down = try wheel(-1)
        terminal.feed(text: "\u{1b}[?1000h\u{1b}[?1006h")
        terminal.scrollWheel(with: up)
        var packets = try reports()
        try check(packets.count == 1 && packets[0][0] == 64, "wheel-up reaches mouse-aware applications")
        try check(packets[0][1] >= 1 && packets[0][1] <= terminal.getTerminal().cols &&
                  packets[0][2] >= 1 && packets[0][2] <= terminal.getTerminal().rows,
                  "wheel coordinates stay inside the visible terminal")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: down)
        packets = try reports()
        try check(packets.count == 1 && packets[0][0] == 65, "wheel-down reaches mouse-aware applications")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: try wheel(3))
        packets = try reports()
        try check(packets.count == 3, "multi-line wheel motion emits the requested number of steps")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: try wheel(1, flags: [.maskAlternate, .maskControl]))
        packets = try reports()
        try check(packets.count == 1 && packets[0][0] == 88, "mouse modifiers are preserved (got \(packets))")
        capture.bytes.removeAll()
        // AppKit converts Shift+wheel into horizontal motion before delivery.
        terminal.scrollWheel(with: try wheel(1, flags: [.maskShift]))
        try check(capture.bytes.isEmpty, "horizontal scrolling does not create a spurious vertical step")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: try wheel(0))
        try check(capture.bytes.isEmpty, "zero wheel motion emits no input")

        // Motion after scrolling back still uses viewport rows, not history rows.
        terminal.feed(text: String(repeating: "history fixture\r\n", count: 150))
        terminal.scrollUp(lines: 40)
        terminal.scrollWheel(with: up)
        packets = try reports()
        try check(packets.count == 1 && packets[0][2] <= terminal.getTerminal().rows,
                  "scrollback offsets do not leak into application mouse coordinates")
        terminal.scroll(toPosition: 1)

        let pixel = try wheel(1, precise: true)
        try check(pixel.hasPreciseScrollingDeltas && pixel.scrollingDeltaY == 1,
                  "test trackpad events use pixel deltas")
        terminal.feed(text: "\u{1b}[?1000l\u{1b}[?1000h")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: pixel)
        try check(capture.bytes.isEmpty, "sub-line trackpad motion does not over-scroll")
        for _ in 0..<100 { terminal.scrollWheel(with: pixel) }
        packets = try reports()
        try check(!packets.isEmpty && packets.count < 20 && packets.allSatisfy { $0[0] == 64 },
                  "trackpad pixels accumulate into bounded whole-line steps")
        terminal.feed(text: "\u{1b}[?1000l\u{1b}[?1000h")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: pixel)
        terminal.scrollWheel(with: try wheel(-1, precise: true))
        try check(capture.bytes.isEmpty, "opposite sub-line deltas cancel without a phantom step")
        terminal.feed(text: "\u{1b}[?1000l\u{1b}[?1000h")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: pixel)
        try check(capture.bytes.isEmpty, "changing mouse mode clears fractional trackpad motion")

        terminal.allowMouseReporting = false
        capture.bytes.removeAll()
        terminal.scrollWheel(with: up)
        try check(capture.bytes.isEmpty, "disabled mouse reporting does not send input to the shell")
        terminal.allowMouseReporting = true
        terminal.feed(text: "\u{1b}[?1000l")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: up)
        try check(capture.bytes.isEmpty, "normal scrollback does not synthesize keys or mouse input")

        for mode in [9, 1000, 1002, 1003] {
            terminal.feed(text: "\u{1b}[?\(mode)h")
            capture.bytes.removeAll()
            terminal.scrollWheel(with: down)
            packets = try reports()
            try check(packets.count == 1 && packets[0][0] == 65, "wheel delivery works in mouse mode \(mode)")
            terminal.feed(text: "\u{1b}[?\(mode)l")
        }
        // Select the encoding before enabling tracking (the pinned release's
        // extended-protocol reset also turns tracking off).
        terminal.feed(text: "\u{1b}[?1006l\u{1b}[?1000h")
        capture.bytes.removeAll()
        terminal.scrollWheel(with: up)
        try check(capture.bytes.count == 6 && capture.bytes.prefix(4) == [27, 91, 77, 96],
                  "legacy X10 wire encoding works (got \(capture.bytes))")
        capture.bytes.removeAll()
        terminal.getTerminal().sendEvent(buttonFlags: 64, x: 1000, y: 1000)
        try check(capture.bytes == [27, 91, 77, 96, 255, 255],
                  "large legacy mouse coordinates clamp without a conversion crash")
        terminal.feed(text: "\u{1b}[?1006h")
        capture.bytes.removeAll()
        let burst = try wheel(3)
        let start = ProcessInfo.processInfo.systemUptime
        for _ in 0..<1000 { terminal.scrollWheel(with: burst) }
        let elapsed = ProcessInfo.processInfo.systemUptime - start
        packets = try reports()
        try check(packets.count == 3000, "1,000 wheel events preserve all 3,000 requested steps")
        print(String(format: "Wheel burst processing: %.2f ms", elapsed * 1000))
    }

    private static func checkWheelPTY(_ terminal: LocalProcessTerminalView, scratch: URL) throws {
        let helper = scratch.appendingPathComponent("wheel_receiver.py")
        try #"""
import os, re, select, sys, termios, time, tty
previous = termios.tcgetattr(0)
data = b""
try:
    tty.setraw(0)
    sys.stdout.write("\x1b[?1000h\x1b[?1006h\r\nWHEEL_RECEIVER_READY\r\n")
    sys.stdout.flush()
    deadline = time.monotonic() + 10
    matches = []
    while len(matches) < 2 and time.monotonic() < deadline:
        if select.select([0], [], [], 0.1)[0]:
            data += os.read(0, 4096)
            matches = re.findall(rb"\x1b\[<(\d+);\d+;\d+M", data)
    result = b",".join(matches).decode("ascii")
finally:
    sys.stdout.write("\x1b[?1000l\x1b[?1006l")
    sys.stdout.flush()
    termios.tcsetattr(0, termios.TCSANOW, previous)
print("\nPTY_WHEEL_RESULT=" + result, flush=True)
"""#.write(to: helper, atomically: true, encoding: .utf8)
        let quoted = "'" + helper.path.replacingOccurrences(of: "'", with: "'\"'\"'") + "'"
        terminal.send(txt: "/usr/bin/python3 \(quoted)\r")
        try wait("real PTY receiver requested mouse input") { text(in: terminal).contains("WHEEL_RECEIVER_READY") }
        terminal.scrollWheel(with: try wheel(1))
        terminal.scrollWheel(with: try wheel(-1))
        try wait("native up/down wheel events reach a real terminal application") {
            text(in: terminal).contains("PTY_WHEEL_RESULT=64,65")
        }
    }

    private static func run() throws {
        let app = NSApplication.shared
        app.setActivationPolicy(.prohibited)
        let manager = FileManager.default
        let scratchRoot = CommandLine.arguments.dropFirst().first.map {
            URL(fileURLWithPath: $0, isDirectory: true)
        } ?? manager.temporaryDirectory
        let scratch = scratchRoot.appendingPathComponent("orkhon-terminal-\(UUID().uuidString)", isDirectory: true)
        let cwd = scratch.appendingPathComponent("cwd with 'quotes' $; spaces", isDirectory: true)
        try manager.createDirectory(at: cwd, withIntermediateDirectories: true)
        let openedFile = cwd.appendingPathComponent("welcome.py")
        try "print('directory fixture')\n".write(to: openedFile, atomically: true, encoding: .utf8)
        defer { try? manager.removeItem(at: scratch) }
        let previousZdotdir = ProcessInfo.processInfo.environment["ZDOTDIR"]
        setenv("ZDOTDIR", scratch.path, 1)
        defer {
            if let previousZdotdir { setenv("ZDOTDIR", previousZdotdir, 1) }
            else { unsetenv("ZDOTDIR") }
        }
        // Deterministic prompt; disable history expansion and background-job renicing.
        // This avoids reading the user's .zshrc and works inside restricted test hosts.
        try "PROMPT='orkhon-test> '; RPROMPT=''; HISTFILE=/dev/null; unsetopt BANG_HIST BGNICE\n"
            .write(to: scratch.appendingPathComponent(".zshrc"), atomically: true, encoding: .utf8)

        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 900, height: 400),
                              styleMask: [.titled, .resizable], backing: .buffered, defer: false)
        let host = NSView(frame: NSRect(x: 0, y: 0, width: 900, height: 400))
        window.contentView = host
        let panel = TerminalPanel(frame: .zero)
        defer {
            panel.terminateAll()
            pumpEvents(for: 0.8) // Allow SwiftTerm's DispatchIO cleanup and child reaping.
            window.contentView = nil
        }
        try check(!panel.hasRunningSessions && terminals(in: panel).isEmpty, "initialization is lazy")
        // Match AppDelegate.toggleTerminal: init → assign cwd → addSubview → ensureSession.
        // A collapsed split-view host can supply a zero frame when the panel is created.
        panel.workingDirectory = openedFile.deletingLastPathComponent()
        host.addSubview(panel)
        panel.frame = host.bounds
        panel.layoutSubtreeIfNeeded()
        pumpEvents(for: 0.05)
        try check(!panel.hasRunningSessions && terminals(in: panel).isEmpty,
                  "attaching and laying out the panel does not start a shell")
        panel.ensureSession()
        let first = try require(terminals(in: panel).first, "first terminal view was not created")
        let firstPID = first.process.shellPid
        try check(first.process.running && firstPID > 1, "zsh owns a live PTY")
        try wait("isolated zsh startup completed") { text(in: first).contains("orkhon-test> ") }
        try checkKeyboardInput(first, window: window)
        try checkWheelInput(first)
        try checkWheelPTY(first, scratch: scratch)
        first.send(txt: "printf '\\nCHECK_TERM=%s\\nCHECK_TTY=%s\\nCHECK_APP=%s\\n' \"$TERM\" \"$(tty)\" \"$TERM_PROGRAM\"\r")
        // Compare the physical directory below: zsh normalizes /private/tmp to /tmp
        // in PWD, although both refer to exactly the same directory.
        try checkPhysicalDirectory(cwd, in: first, marker: "FIRST_PHYSICAL_CWD",
                                   label: "parent creation sequence uses the opened file's physical directory")
        try wait("real TTY and xterm-256color environment") {
            text(in: first).contains("CHECK_TERM=xterm-256color") && text(in: first).contains("CHECK_TTY=/dev/")
        }
        try wait("terminal identifies the app as Orkhon Code") {
            text(in: first).contains("CHECK_APP=Orkhon Code")
        }
        panel.ensureSession()
        try check(terminals(in: panel).count == 1, "ensureSession does not duplicate a live tab")

        let oldColumns = first.getTerminal().cols
        panel.setFrameSize(NSSize(width: 580, height: 260))
        panel.layoutSubtreeIfNeeded()
        var size = winsize()
        let resizeResult = ioctl(first.process.childfd, TIOCGWINSZ, &size)
        try check(resizeResult == 0 && first.getTerminal().cols < oldColumns &&
                  Int(size.ws_col) == first.getTerminal().cols && Int(size.ws_row) == first.getTerminal().rows,
                  "resizing reaches the PTY rows and columns")
        panel.applyTheme(background: .black, foreground: .white, accent: .systemGreen)
        try check(first.nativeBackgroundColor == .black && first.nativeForegroundColor == .white &&
                  first.caretColor == .systemGreen, "theme updates native background, text, and cursor")

        first.send(txt: "sleep 60\r")
        try wait("foreground job started") {
            let group = tcgetpgrp(first.process.childfd)
            return group > 1 && group != firstPID
        }
        let interrupt = try require(NSEvent.keyEvent(
            with: .keyDown, location: .zero, modifierFlags: .control, timestamp: 0,
            windowNumber: window.windowNumber, context: nil, characters: "c",
            charactersIgnoringModifiers: "c", isARepeat: false, keyCode: 8
        ), "could not construct the native Control-C event")
        first.keyDown(with: interrupt)
        try wait("native Control-C returns foreground control to zsh") {
            tcgetpgrp(first.process.childfd) == firstPID
        }
        first.send(txt: "printf '\\nCHECK_%s\\n' INTERRUPTED\r")
        try wait("shell accepts input after Control-C") { text(in: first).contains("CHECK_INTERRUPTED") }

        let nextDirectory = scratch.appendingPathComponent("next workspace", isDirectory: true)
        try manager.createDirectory(at: nextDirectory, withIntermediateDirectories: true)
        panel.workingDirectory = nextDirectory
        panel.ensureSession()
        try check(terminals(in: panel).count == 1 && first.process.shellPid == firstPID,
                  "changing cwd and reopening preserves the existing shell")
        try checkPhysicalDirectory(cwd, in: first, marker: "EXISTING_PHYSICAL_CWD",
                                   label: "changing the default cwd does not move an active shell")

        let plus = try require(descendants(of: panel).compactMap { $0 as? NSButton }.first {
            $0.toolTip?.hasPrefix("New Terminal (") == true
        }, "new-terminal button was not found")
        plus.performClick(nil)
        try check(terminals(in: panel).count == 2, "new button creates a second terminal tab")
        let second = try require(terminals(in: panel).first { $0 !== first }, "second terminal was not found")
        let secondPID = second.process.shellPid
        try check(secondPID > 1 && secondPID != firstPID && first.isHidden && !second.isHidden,
                  "tabs preserve independent processes and selection")
        try wait("second shell is ready") { text(in: second).contains("orkhon-test> ") }
        try checkPhysicalDirectory(nextDirectory, in: second, marker: "NEXT_PHYSICAL_CWD",
                                   label: "a new tab uses the updated physical working directory")
        second.send(txt: "sleep 60 &\r")
        try wait("background job started") { child(inSession: secondPID) != nil }
        let backgroundPID = try require(child(inSession: secondPID), "background job disappeared unexpectedly")
        let close = try require(descendants(of: panel).compactMap { $0 as? NSButton }.first {
            $0.toolTip == "Close terminal 2"
        }, "second terminal's close button was not found")
        close.performClick(nil)
        try check(terminals(in: panel).count == 1 && !first.isHidden, "closing a tab selects its neighbor")
        try wait("closing a tab cleans up its shell and background job") {
            isGone(secondPID) && isGone(backgroundPID)
        }

        // More than SwiftTerm's 128 KiB PTY read size. Checking a distinct final marker
        // catches closing DispatchIO before all reads are delivered after shell exit.
        first.send(txt: "for i in {1..30000}; do print -r -- $i; done; printf '\\nFINAL_%s\\n' OUTPUT; exit 7\r")
        try wait("natural exit updates running-session state", timeout: 15) { !panel.hasRunningSessions }
        try check(terminals(in: panel).count == 1, "exited tab preserves its scrollback")
        try wait("30,000-line final output survives natural exit") { text(in: first).contains("FINAL_OUTPUT") }
        try wait("raw wait status is normalized to exit code 7") {
            descendants(of: panel).compactMap(\.toolTip).joined().contains("Exited with status 7")
        }
        panel.ensureSession()
        try check(terminals(in: panel).count == 2 && panel.hasRunningSessions, "ensureSession replaces an exited shell")
        let final = try require(terminals(in: panel).last, "replacement terminal was not found")
        let finalPID = final.process.shellPid
        panel.terminateAll()
        panel.terminateAll()
        try wait("shutdown is idempotent and reaps the shell") {
            !panel.hasRunningSessions && terminals(in: panel).isEmpty && isGone(finalPID)
        }
    }
}
